### ISSUE TITLE
Small issue with torch version number under colab

### ISSUE THREAD

**Issue by sfoucher** [plstcharles/thelper#10]
Hello Pierre-Luc,

Weird issue with thelper using Google colab:

```
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.6/dist-packages/thelper/data/loaders.py", line 39, in default_collate
    torch_ver = [int(v) for v in torch.__version__.split(".")]
  File "/usr/local/lib/python3.6/dist-packages/thelper/data/loaders.py", line 39, in <listcomp>
    torch_ver = [int(v) for v in torch.__version__.split(".")]
ValueError: invalid literal for int() with base 10: '0+cu101'
```

For some reason I get:
```print(torch.__version__)= 1.5.0+cu101```

cu101 seems to indicate CUDA 10.1

so `torch_ver = [int(v) for v in torch.__version__.split(".")]` in default_collate crashes.

Samuel

**Comment by plstcharles** [comment]
Good catch, thanks! Interesting bug, but probably easy to fix --- I'm currently packing stuff to move over the weekend, but will try to fix ASAP (when the computer is unpacked again...)

**Comment by fmigneault** [comment]
@plstcharles  just do `torch.__version__.split('+')[0].split(".")`
